In [40]:
%reload_ext autoreload
%autoreload 2
%reload_ext notexbook
%texify

#### Run the experiment notebooks for the following notebooks
1. ../expt_notebooks/EXP-21-BV6157 Cipro-1 concentration.ipynb
2. ../expt_notebooks/EXP-21-BV6160 Gentamycin 2ugml concentration.ipynb
3. ../expt_notebooks/EXP-21-BV6171 nitrofurantoin 32ugml concentration.ipynb
4. ../expt_notebooks/EXP-21-BV6174 vancomycin 4ugml concentration.ipynb

To get the growth rates curves of all the experiments



#### There are fig handles to save figures automatically, you have to save them once are plotted

In [41]:
from narsil2.mm.growth import growth_rate_pickles
from pathlib import Path
import numpy as np
%matplotlib qt5

In [42]:
root_dir = '/mnt/sda2/Praneeth/ASTFISH/'

### First experiment cipro 1ug/ml

In [43]:

analysis_main_dir = Path(root_dir + 'analysis_rev/EXP-21-BV6157 AST FISH 210520')
species_names = ['Klebsiella', 'E.coli', 'Pseudomonas', 'E.cocci']
species_titles = []
No_Ab_Positions = list(range(101, 175))
Ab_Positions = list(range(201, 275))
tracking_parameters = {
    'move_iou_thres': 0.15,
    'div_iou_thres' : 0.15,
    'write_dir_names': {
        'channel_stacks': 'blobs',
        'growth_rates': 'growth_rates',
        'fluor_stacks': 'fish_channels',
    },
    'growth_type': 'rolling', # or 'ratio'
    'net_path': '../../saved_models/tracker_model.pth',
    'species_map': {
        'Klebsiella': {'cy5'},
        'E.coli' : {'cy3'},
        'Pseudomonas': {'texasred'},
        'E.cocci': {'alexa488'}
    },
    'background_channel_no': 15,
    'flip_positions': range(201, 276),
    'num_channels': 32,
    'growth_type': 'rolling'
}
g = growth_rate_pickles(analysis_main_dir, species_names, species_titles,
                        No_Ab_Positions=No_Ab_Positions, Ab_Positions=Ab_Positions,
                        tracking_parameters=tracking_parameters,
                        antibiotic_concentration=1,
                        antibiotic_name='Ciprofloxacin',
                       n_frames=30)
color_scheme = {
    'Klebsiella': 'r', 'E.coli': 'b', 'E.cocci': 'c', 'Pseudomonas': 'g'
}
g.plot_species_wise_and_pooled(color_scheme=color_scheme)

In [44]:
g.species_names

['Klebsiella', 'E.coli', 'Pseudomonas', 'E.cocci']

In [45]:
g.No_Ab_Clean_Pooled_GrowthRates

(array([0.        , 0.        , 0.        , 0.        , 0.01465507,
        0.01499611, 0.01537326, 0.01578584, 0.01582534, 0.01587081,
        0.01591501, 0.0160353 , 0.01623664, 0.01638382, 0.01627522,
        0.01610679, 0.01617763, 0.01622528, 0.01618917, 0.01615722,
        0.01611842, 0.01617318, 0.01625041, 0.01633717, 0.0164263 ,
        0.01647537, 0.01666745, 0.01678725, 0.01699595, 0.01703698]),
 array([0.        , 0.        , 0.        , 0.        , 0.0057829 ,
        0.00566758, 0.00577611, 0.00574122, 0.00574599, 0.00554758,
        0.00574329, 0.00564691, 0.00560698, 0.00571795, 0.005655  ,
        0.00569937, 0.00592507, 0.00564475, 0.00587531, 0.00586351,
        0.00586419, 0.00592178, 0.00593963, 0.00616964, 0.00646246,
        0.00628586, 0.00636483, 0.00652516, 0.00669014, 0.00660685]),
 array([   0.,    0.,    0.,    0., 3146., 3306., 3449., 3563., 3716.,
        3865., 4032., 4192., 4411., 4608., 4833., 5022., 5189., 5469.,
        5685., 5884., 6137., 6359., 66

In [46]:
def get_raw_data(g, species):
    if species != 'pool_Ab' and species != 'pool_no_Ab':
        print(f'{species} Normalized growth rates Ab response, sem of growth rate, time')
        species_noab = g.No_Ab_Clean_GrowthRates[species]
        species_ab = g.Ab_Clean_GrowthRates[species]
        normalized_growth_rates = species_ab[0]/species_noab[0]
        species_error_ab = species_ab[1]/species_noab[0]/np.sqrt(species_ab[2])
        return (normalized_growth_rates, species_error_ab, np.array(list(range(0, 2 * g.n_frames, 2))))
    elif species == 'pool_no_Ab':
        print(f'{species} ones, sem of pooled growth rate, time')

        noAb_pool = g.No_Ab_Clean_Pooled_GrowthRates
        Ab_pool = g.Ab_Clean_Pooled_GrowthRates
        ones = np.array([1] * g.n_frames)
        noAb_pool_err = noAb_pool[1]/ noAb_pool[0]/ np.sqrt(noAb_pool[2])
        return (ones, noAb_pool_err, np.array(list(range(0, 2 * g.n_frames, 2))))
    
    elif species == 'pool_Ab':
        print(f'{species} normalized growth rates, sem of pooled growth rate, time')
        noAb_pool = g.No_Ab_Clean_Pooled_GrowthRates
        Ab_pool = g.Ab_Clean_Pooled_GrowthRates
        normalized_pool = Ab_pool[0]/noAb_pool[0]
        Ab_pool_err = Ab_pool[1]/noAb_pool[0]/np.sqrt(Ab_pool[2])
        return (normalized_pool, Ab_pool_err, np.array(list(range(0, 2 * g.n_frames, 2))))
    

In [47]:
get_raw_data(g, 'Klebsiella')

Klebsiella Normalized growth rates Ab response, sem of growth rate, time


(array([       nan,        nan,        nan,        nan, 0.96482402,
        0.9445093 , 0.94298301, 0.92139942, 0.91862958, 0.9056019 ,
        0.92463813, 0.91474941, 0.91175784, 0.9054766 , 0.89737416,
        0.89595698, 0.87634464, 0.87532919, 0.85458134, 0.84711755,
        0.83699437, 0.82239456, 0.81269738, 0.79501355, 0.78363854,
        0.77035766, 0.74950723, 0.73086307, 0.71639224, 0.70346459]),
 array([       nan,        nan,        nan,        nan, 0.01479322,
        0.01339003, 0.01223649, 0.0111799 , 0.01074985, 0.01112798,
        0.01337924, 0.0107805 , 0.00946589, 0.00744839, 0.00710419,
        0.00698572, 0.00647469, 0.006219  , 0.00689752, 0.00652627,
        0.00672299, 0.00686025, 0.00737715, 0.00646035, 0.00587531,
        0.00545535, 0.00567512, 0.005629  , 0.00564943, 0.00549674]),
 array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
        34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58]))

In [48]:
get_raw_data(g, 'E.coli')

E.coli Normalized growth rates Ab response, sem of growth rate, time


(array([       nan,        nan,        nan,        nan, 0.97630105,
        0.90362311, 0.83357375, 0.78584259, 0.76016001, 0.7559461 ,
        0.76489713, 0.75689198, 0.75191596, 0.74384943, 0.72115939,
        0.69826375, 0.69719295, 0.67951871, 0.68045942, 0.67779887,
        0.6792745 , 0.67123646, 0.65266682, 0.64086773, 0.63080042,
        0.63202645, 0.62053541, 0.60133813, 0.59031808, 0.59646073]),
 array([       nan,        nan,        nan,        nan, 0.01832545,
        0.01841117, 0.01617799, 0.01660822, 0.01497098, 0.01438249,
        0.01653242, 0.01334388, 0.01225017, 0.01026591, 0.00918807,
        0.00854615, 0.00848871, 0.00877583, 0.00864559, 0.0081028 ,
        0.00774228, 0.00824352, 0.00752624, 0.00744838, 0.00822875,
        0.00818634, 0.00841042, 0.00917985, 0.00934646, 0.00923397]),
 array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
        34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58]))

In [49]:
get_raw_data(g, 'Pseudomonas')

Pseudomonas Normalized growth rates Ab response, sem of growth rate, time


(array([       nan,        nan,        nan,        nan, 1.00435024,
        1.02497312, 1.02800754, 0.98312791, 0.97276842, 0.96069952,
        1.00690063, 0.99543704, 0.99725236, 0.97999064, 0.97028723,
        0.9869684 , 0.96105806, 0.96730482, 0.961344  , 0.96357304,
        0.96745583, 0.93981412, 0.94535239, 0.96337594, 0.96529347,
        0.97850949, 0.95150435, 0.94721813, 0.94523017, 0.94591661]),
 array([       nan,        nan,        nan,        nan, 0.02443431,
        0.02469191, 0.0224304 , 0.02160612, 0.01806733, 0.01814962,
        0.02169141, 0.01842274, 0.0164824 , 0.01716694, 0.01580183,
        0.01685029, 0.01631863, 0.01590672, 0.01547972, 0.01495432,
        0.01502401, 0.0137904 , 0.01462228, 0.01591284, 0.01488959,
        0.01399333, 0.01311334, 0.01274456, 0.01308784, 0.01272993]),
 array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
        34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58]))

In [50]:
get_raw_data(g, 'E.cocci')

E.cocci Normalized growth rates Ab response, sem of growth rate, time


(array([       nan,        nan,        nan,        nan, 0.93966421,
        0.92751695, 0.92242411, 0.90286027, 0.92383261, 0.94031077,
        0.94931285, 0.95172522, 0.94980503, 0.93630302, 0.94293474,
        0.94954895, 0.9357712 , 0.93326119, 0.92324013, 0.92628065,
        0.92555009, 0.92448239, 0.92347269, 0.91219946, 0.90561281,
        0.90502589, 0.90412072, 0.89719835, 0.87728581, 0.85790989]),
 array([       nan,        nan,        nan,        nan, 0.00918513,
        0.0084528 , 0.0079517 , 0.00775797, 0.00781781, 0.00782654,
        0.00758803, 0.00739219, 0.00735849, 0.00725139, 0.00719147,
        0.00761366, 0.00734234, 0.00719599, 0.00705734, 0.00676417,
        0.0066959 , 0.00654205, 0.00640995, 0.00630677, 0.00616399,
        0.00591522, 0.00605255, 0.00581613, 0.00554873, 0.00540669]),
 array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
        34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58]))

In [51]:
get_raw_data(g, 'pool_Ab')

pool_Ab normalized growth rates, sem of pooled growth rate, time


(array([       nan,        nan,        nan,        nan, 0.95873674,
        0.94108434, 0.92929271, 0.9005438 , 0.90646701, 0.91112211,
        0.92567246, 0.92262138, 0.91973777, 0.90774917, 0.90414922,
        0.90501388, 0.89077509, 0.88569731, 0.87573089, 0.87609758,
        0.87427106, 0.86508408, 0.85966775, 0.85204762, 0.84659701,
        0.84734755, 0.83849877, 0.82877555, 0.81749429, 0.80935963]),
 array([       nan,        nan,        nan,        nan, 0.00713711,
        0.00677824, 0.00633836, 0.0061946 , 0.00595167, 0.00590933,
        0.0062109 , 0.00559158, 0.00530045, 0.0050746 , 0.00488986,
        0.00509144, 0.00490034, 0.00481108, 0.00474575, 0.00456627,
        0.00453529, 0.00441203, 0.00442155, 0.0044831 , 0.00436993,
        0.00419124, 0.00420803, 0.00413485, 0.00413169, 0.00408631]),
 array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
        34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58]))

In [52]:
get_raw_data(g, 'pool_no_Ab')

pool_no_Ab ones, sem of pooled growth rate, time


(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1]),
 array([       nan,        nan,        nan,        nan, 0.00703524,
        0.00657306, 0.00639769, 0.00609297, 0.00595627, 0.00562251,
        0.00568321, 0.00543905, 0.00519954, 0.00514126, 0.00499801,
        0.0049932 , 0.00508437, 0.00470434, 0.00481327, 0.00473102,
        0.00464416, 0.00459158, 0.00449533, 0.0045463 , 0.00464685,
        0.00440524, 0.00430621, 0.00427063, 0.0042105 , 0.00401456]),
 array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
        34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58]))

In [53]:
get_raw_data(g, 'pool_Ab')

pool_Ab normalized growth rates, sem of pooled growth rate, time


(array([       nan,        nan,        nan,        nan, 0.95873674,
        0.94108434, 0.92929271, 0.9005438 , 0.90646701, 0.91112211,
        0.92567246, 0.92262138, 0.91973777, 0.90774917, 0.90414922,
        0.90501388, 0.89077509, 0.88569731, 0.87573089, 0.87609758,
        0.87427106, 0.86508408, 0.85966775, 0.85204762, 0.84659701,
        0.84734755, 0.83849877, 0.82877555, 0.81749429, 0.80935963]),
 array([       nan,        nan,        nan,        nan, 0.00713711,
        0.00677824, 0.00633836, 0.0061946 , 0.00595167, 0.00590933,
        0.0062109 , 0.00559158, 0.00530045, 0.0050746 , 0.00488986,
        0.00509144, 0.00490034, 0.00481108, 0.00474575, 0.00456627,
        0.00453529, 0.00441203, 0.00442155, 0.0044831 , 0.00436993,
        0.00419124, 0.00420803, 0.00413485, 0.00413169, 0.00408631]),
 array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
        34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58]))

### Second experiment nitrofurantoin 32ug/ml

In [56]:
species_names = ['Klebsiella', 'E.coli', 'Pseudomonas', 'E.cocci']
species_titles = []
No_Ab_Positions = list(range(101, 183))
Ab_Positions = list(range(201, 283))
analysis_dir = root_dir + 'analysis_rev/EXP-21-BV6171 AST FISH 210630/'
tracking_parameters = {
    'move_iou_thres': 0.15,
    'div_iou_thres' : 0.15,
    'write_dir_names': {
        'channel_stacks': 'blobs',
        'growth_rates': 'growth_rates',
        'fluor_stacks': 'fish_channels',
    },
    'growth_type': 'rolling', # or 'ratio'
    'net_path': '../../saved_models/tracker_model.pth',
    'species_map': {
        'Klebsiella': {'cy5'},
        'E.coli' : {'cy3'},
        'Pseudomonas': {'texasred'},
        'E.cocci': {'alexa488'}
    },
    'background_channel_no': 17,
    'flip_positions': range(201, 283),
    'num_channels': 36,
    'growth_type': 'rolling'
}
g = growth_rate_pickles(Path(analysis_dir), species_names, species_titles,
                        No_Ab_Positions=No_Ab_Positions, Ab_Positions=Ab_Positions,
                        tracking_parameters=tracking_parameters,
                        antibiotic_concentration=32,
                        antibiotic_name='Nitrofurantoin',
                       n_frames=30)
color_scheme = {
    'Klebsiella': 'r', 'E.coli': 'b', 'E.cocci': 'c', 'Pseudomonas': 'g'
}
g.plot_species_wise_and_pooled(color_scheme=color_scheme)

In [57]:
get_raw_data(g, 'Klebsiella')

Klebsiella Normalized growth rates Ab response, sem of growth rate, time


(array([       nan,        nan,        nan,        nan, 0.9738517 ,
        0.81069088, 0.58249007, 0.39561347, 0.28947267, 0.26666952,
        0.2650639 , 0.26499112, 0.26983934, 0.27430046, 0.27834074,
        0.2794861 , 0.27541273, 0.27193543, 0.26847403, 0.26493797,
        0.26323099, 0.2560574 , 0.24892085, 0.24738065, 0.24135284,
        0.2331262 , 0.22773629, 0.22903654, 0.22175408, 0.22134182]),
 array([       nan,        nan,        nan,        nan, 0.00927995,
        0.0083546 , 0.00782392, 0.0069967 , 0.00591596, 0.00538542,
        0.00518244, 0.00596672, 0.00547209, 0.00481171, 0.00533553,
        0.00548137, 0.00633737, 0.00476774, 0.00421997, 0.00442847,
        0.00441527, 0.00414477, 0.00423212, 0.004161  , 0.0039444 ,
        0.00393001, 0.00390308, 0.00476995, 0.00440851, 0.00427446]),
 array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
        34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58]))

In [58]:
get_raw_data(g, 'E.coli')

E.coli Normalized growth rates Ab response, sem of growth rate, time


(array([       nan,        nan,        nan,        nan, 0.9595477 ,
        0.78895324, 0.5518306 , 0.37511015, 0.27727616, 0.25165823,
        0.23194925, 0.21732702, 0.20643996, 0.20557507, 0.20454369,
        0.19303304, 0.18943183, 0.1806639 , 0.17712256, 0.16513449,
        0.16626342, 0.15119654, 0.14888025, 0.14538178, 0.1396028 ,
        0.13950677, 0.13329249, 0.1309698 , 0.12758382, 0.1320143 ]),
 array([       nan,        nan,        nan,        nan, 0.00797185,
        0.00759464, 0.00600725, 0.00526953, 0.00496848, 0.00486886,
        0.00430382, 0.00483058, 0.00490707, 0.00496934, 0.00555819,
        0.00462145, 0.0052376 , 0.00456016, 0.00456467, 0.00396518,
        0.00408668, 0.00281324, 0.00336104, 0.00341383, 0.00330733,
        0.00355945, 0.00328063, 0.00351264, 0.00352815, 0.00414715]),
 array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
        34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58]))

In [59]:
get_raw_data(g, 'Pseudomonas')

Pseudomonas Normalized growth rates Ab response, sem of growth rate, time


(array([       nan,        nan,        nan,        nan, 0.94121144,
        0.93045898, 0.94734823, 0.88568194, 0.88919297, 0.86461965,
        0.84499489, 0.88031568, 0.79247427, 0.81730402, 0.83086642,
        0.79064877, 0.80894892, 0.77974003, 0.81304475, 0.84602937,
        0.82576845, 0.83558364, 0.83289924, 0.86285587, 0.87005216,
        0.87410604, 0.85428377, 0.83535474, 0.87787996, 0.87278695]),
 array([       nan,        nan,        nan,        nan, 0.03589413,
        0.03626254, 0.03979666, 0.04025315, 0.03907272, 0.04480264,
        0.04022031, 0.0371641 , 0.0313645 , 0.03237948, 0.0315418 ,
        0.02876198, 0.02969773, 0.02945357, 0.02880119, 0.02741778,
        0.0242535 , 0.02502139, 0.02355805, 0.02454935, 0.02168096,
        0.02311566, 0.02188644, 0.01951841, 0.01852095, 0.018643  ]),
 array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
        34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58]))

In [60]:
get_raw_data(g, 'pool_no_Ab')

pool_no_Ab ones, sem of pooled growth rate, time


(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1]),
 array([       nan,        nan,        nan,        nan, 0.00579591,
        0.00567181, 0.0050266 , 0.00498065, 0.00530734, 0.00497547,
        0.00486557, 0.00468133, 0.00439931, 0.00408297, 0.00395326,
        0.00398016, 0.0037782 , 0.00378526, 0.00397429, 0.00384092,
        0.00370221, 0.00374643, 0.00375527, 0.00348368, 0.00334399,
        0.00330877, 0.003092  , 0.00300613, 0.00308394, 0.00299674]),
 array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
        34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58]))

In [61]:
get_raw_data(g, 'pool_Ab')

pool_Ab normalized growth rates, sem of pooled growth rate, time


(array([       nan,        nan,        nan,        nan, 0.94903252,
        0.79694248, 0.59034075, 0.42386709, 0.32916777, 0.30381908,
        0.29062999, 0.28217465, 0.27347938, 0.27279439, 0.27332567,
        0.26795823, 0.26915466, 0.26588685, 0.26247864, 0.25587169,
        0.26047863, 0.25090689, 0.24728306, 0.24782252, 0.24294047,
        0.24377626, 0.2419412 , 0.24608047, 0.25312609, 0.26306616]),
 array([       nan,        nan,        nan,        nan, 0.0060863 ,
        0.00572644, 0.00505123, 0.00478524, 0.00455669, 0.00455685,
        0.0043244 , 0.00456816, 0.00438698, 0.00427789, 0.00458134,
        0.0042482 , 0.00474245, 0.00446185, 0.00431205, 0.00407109,
        0.00414171, 0.00387681, 0.00394388, 0.00407341, 0.00384832,
        0.00407146, 0.00401299, 0.00411858, 0.00417382, 0.00450349]),
 array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
        34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58]))

#### Third experiment Gentamycin 2ug/ml

In [62]:
species_names = ['Klebsiella', 'E.coli', 'Pseudomonas', 'E.cocci']
species_titles = []
No_Ab_Positions = list(range(101, 172))
Ab_Positions = list(range(201, 272))
analysis_dir = root_dir + 'analysis_rev/EXP-21-BV6160 AST FISH 210525/'
tracking_parameters = {
    'move_iou_thres': 0.15,
    'div_iou_thres' : 0.15,
    'write_dir_names': {
        'channel_stacks': 'blobs',
        'growth_rates': 'growth_rates',
        'fluor_stacks': 'fish_channels',
    },
    'growth_type': 'rolling', # or 'ratio'
    'net_path': '../../saved_models/tracker_model.pth',
    'species_map': {
        'Klebsiella': {'cy5'},
        'E.coli' : {'cy3'},
        'Pseudomonas': {'texasred'},
        'E.cocci': {'alexa488'}
    },
    'background_channel_no': 15,
    'flip_positions': range(201, 272),
    'num_channels': 32,
    'growth_type': 'rolling'
}
g = growth_rate_pickles(Path(analysis_dir), species_names, species_titles,
                        No_Ab_Positions=No_Ab_Positions, Ab_Positions=Ab_Positions,
                        tracking_parameters=tracking_parameters,
                        antibiotic_concentration=2,
                        antibiotic_name='Gentamycin',
                       n_frames=30)
color_scheme = {
    'Klebsiella': 'r', 'E.coli': 'b', 'E.cocci': 'c', 'Pseudomonas': 'g'
}
g.plot_species_wise_and_pooled(color_scheme=color_scheme)

In [63]:
get_raw_data(g, 'Klebsiella')

Klebsiella Normalized growth rates Ab response, sem of growth rate, time


(array([       nan,        nan,        nan,        nan, 0.84151293,
        0.90499555, 0.94271767, 0.95615338, 0.95475794, 0.97003881,
        0.97431135, 0.96766824, 0.97573018, 0.97380526, 0.9642133 ,
        0.93257281, 0.88642258, 0.85800003, 0.81315818, 0.77968764,
        0.72641134, 0.65183152, 0.6008034 , 0.55290695, 0.50191209,
        0.44612536, 0.39266534, 0.34804842, 0.32168415, 0.29766171]),
 array([       nan,        nan,        nan,        nan, 0.01062882,
        0.01211669, 0.01242609, 0.01205892, 0.01089817, 0.01012046,
        0.01000703, 0.00979453, 0.01012617, 0.00969484, 0.00948933,
        0.00887282, 0.00840418, 0.00864452, 0.00859526, 0.00886486,
        0.00877347, 0.00890402, 0.00917882, 0.00868618, 0.00791768,
        0.00723101, 0.00646667, 0.00612772, 0.00568915, 0.00537742]),
 array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
        34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58]))

In [64]:
get_raw_data(g, 'E.coli')

E.coli Normalized growth rates Ab response, sem of growth rate, time


(array([       nan,        nan,        nan,        nan, 0.89322296,
        0.90111593, 0.93094842, 0.96737533, 0.93299072, 0.96331353,
        0.971438  , 0.96396748, 0.96870124, 0.94245804, 0.96805583,
        0.97887521, 0.9434731 , 0.89047063, 0.84988744, 0.81989865,
        0.780182  , 0.70916623, 0.65553606, 0.59791427, 0.55230681,
        0.50201536, 0.45459923, 0.43129908, 0.4025096 , 0.37524959]),
 array([       nan,        nan,        nan,        nan, 0.01910957,
        0.0197632 , 0.02229223, 0.02404961, 0.01989821, 0.0219973 ,
        0.02216057, 0.02267705, 0.01957745, 0.0149413 , 0.01489692,
        0.01393502, 0.01423916, 0.01381793, 0.01438664, 0.01359261,
        0.01327604, 0.01326693, 0.01406295, 0.01320921, 0.01311014,
        0.01161037, 0.0106716 , 0.01029142, 0.01031938, 0.0099827 ]),
 array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
        34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58]))

In [65]:
get_raw_data(g, 'E.cocci')

E.cocci Normalized growth rates Ab response, sem of growth rate, time


(array([       nan,        nan,        nan,        nan, 0.91541447,
        0.91974505, 0.91957076, 0.91463413, 0.93350301, 0.95076904,
        0.95782999, 0.98289168, 1.0031058 , 0.99853844, 0.98963229,
        0.99654883, 0.99792368, 0.98098158, 0.94612785, 0.97040936,
        0.98183227, 0.99758784, 1.00915918, 0.9933786 , 0.98639117,
        0.98380634, 0.97536272, 0.95030227, 0.96471992, 0.95472001]),
 array([       nan,        nan,        nan,        nan, 0.01286128,
        0.01220436, 0.01289714, 0.01295832, 0.01313731, 0.01257105,
        0.01205578, 0.0125904 , 0.01263162, 0.01228438, 0.01147143,
        0.01040762, 0.01095826, 0.01059695, 0.0099936 , 0.01024178,
        0.01006497, 0.01000597, 0.00948844, 0.00955279, 0.00962246,
        0.00920814, 0.00863889, 0.00845008, 0.00850585, 0.00903206]),
 array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
        34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58]))

In [66]:
get_raw_data(g, 'Pseudomonas')

Pseudomonas Normalized growth rates Ab response, sem of growth rate, time


(array([       nan,        nan,        nan,        nan, 1.11774107,
        1.23809312, 0.9962296 , 1.03177889, 1.11342673, 1.27988975,
        1.07374811, 1.05661784, 1.04143026, 0.97929146, 0.88579139,
        0.85935846, 0.78967974, 0.79287389, 0.85737884, 0.82097451,
        0.80944152, 0.76671445, 0.71418114, 0.71545227, 0.70530504,
        0.68512855, 0.60647015, 0.59806865, 0.58051637, 0.55652353]),
 array([       nan,        nan,        nan,        nan, 0.12112017,
        0.14132824, 0.06486023, 0.0840491 , 0.12063832, 0.12172749,
        0.08084141, 0.05349044, 0.05740448, 0.05923885, 0.04599081,
        0.03859308, 0.03143933, 0.03331668, 0.04231942, 0.04163462,
        0.04064795, 0.03774014, 0.02938054, 0.02867218, 0.02761392,
        0.03194633, 0.02811531, 0.02763946, 0.02658528, 0.02348257]),
 array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
        34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58]))

In [69]:
get_raw_data(g, 'pool_no_Ab')

pool_no_Ab ones, sem of pooled growth rate, time


(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1]),
 array([       nan,        nan,        nan,        nan, 0.021176  ,
        0.01553782, 0.01293343, 0.0118903 , 0.00977034, 0.00803326,
        0.0082233 , 0.00715935, 0.00682304, 0.00658554, 0.00608603,
        0.00571654, 0.00600345, 0.00552905, 0.00507913, 0.00505434,
        0.00496246, 0.00475727, 0.00464398, 0.00470535, 0.00466271,
        0.00443776, 0.00437953, 0.00447535, 0.00443656, 0.00439252]),
 array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
        34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58]))

In [71]:
get_raw_data(g, 'pool_Ab')

pool_Ab normalized growth rates, sem of pooled growth rate, time


(array([       nan,        nan,        nan,        nan, 0.87615795,
        0.91241144, 0.93280498, 0.9451107 , 0.95464993, 0.97402852,
        0.97677823, 0.98047867, 0.99139664, 0.98232445, 0.97441318,
        0.96241585, 0.93219729, 0.90501359, 0.86876388, 0.85545155,
        0.82921291, 0.78658525, 0.75659666, 0.72224613, 0.68941658,
        0.65387933, 0.6164824 , 0.58862404, 0.57502826, 0.5570762 ]),
 array([       nan,        nan,        nan,        nan, 0.00806802,
        0.00849586, 0.0083624 , 0.00850895, 0.00845098, 0.00805122,
        0.00773708, 0.0076186 , 0.00752933, 0.00702868, 0.0066733 ,
        0.00612202, 0.00608076, 0.00606865, 0.00611729, 0.00622137,
        0.00618589, 0.00626076, 0.00627632, 0.00618593, 0.00608104,
        0.0059667 , 0.00569905, 0.00563809, 0.00565014, 0.00563642]),
 array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
        34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58]))

#### Fourth experiment Vancomycin 4ug/ml

In [72]:
species_names = ['Klebsiella', 'E.coli', 'Pseudomonas', 'E.cocci']
species_titles = []
No_Ab_Positions = list(range(101, 176))
Ab_Positions = list(range(201, 276))
analysis_dir = root_dir + 'analysis_rev/EXP-21-BV6174 AST FISH 210704/'
tracking_parameters = {
    'move_iou_thres': 0.15,
    'div_iou_thres' : 0.15,
    'write_dir_names': {
        'channel_stacks': 'blobs',
        'growth_rates': 'growth_rates',
        'fluor_stacks': 'fish_channels',
    },
    'growth_type': 'rolling', # or 'ratio'
    'net_path': '../../saved_models/tracker_model.pth',
    'species_map': {
        'Klebsiella': {'cy5'},
        'E.coli' : {'cy3'},
        'Pseudomonas': {'texasred'},
        'E.cocci': {'alexa488'}
    },
    'background_channel_no': 15,
    'flip_positions': range(201, 276),
    'num_channels': 32,
    'growth_type': 'rolling'
}
g = growth_rate_pickles(Path(analysis_dir), species_names, species_titles,
                        No_Ab_Positions=No_Ab_Positions, Ab_Positions=Ab_Positions,
                        tracking_parameters=tracking_parameters,
                        antibiotic_concentration=4,
                        antibiotic_name='Vancomycin',
                       n_frames=30)
color_scheme = {
    'Klebsiella': 'r', 'E.coli': 'b', 'E.cocci': 'c', 'Pseudomonas': 'g'
}
g.plot_species_wise_and_pooled(color_scheme=color_scheme)

In [73]:
get_raw_data(g, 'Klebsiella')

Klebsiella Normalized growth rates Ab response, sem of growth rate, time


(array([       nan,        nan,        nan,        nan, 0.93388481,
        0.94570578, 0.97375595, 0.98010597, 0.98733503, 0.99444231,
        0.98134866, 0.97954449, 0.98636966, 0.98384589, 0.98945861,
        0.9866305 , 0.99272415, 0.99883652, 0.99574982, 0.97766396,
        0.97121158, 0.97202231, 0.97744319, 0.97938941, 0.96253583,
        0.96070097, 0.95401655, 0.95275579, 0.96013067, 0.96266549]),
 array([       nan,        nan,        nan,        nan, 0.00656224,
        0.00625577, 0.0061973 , 0.00613128, 0.00599577, 0.00562213,
        0.00532346, 0.00522074, 0.00532329, 0.00523186, 0.00526147,
        0.00464655, 0.00439873, 0.00433743, 0.00431703, 0.00419984,
        0.0039654 , 0.00382208, 0.00369452, 0.00353928, 0.00336144,
        0.00323197, 0.00328774, 0.003311  , 0.00320542, 0.00311787]),
 array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
        34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58]))

In [74]:
get_raw_data(g, 'E.coli')

E.coli Normalized growth rates Ab response, sem of growth rate, time


(array([       nan,        nan,        nan,        nan, 0.89733882,
        0.91844754, 0.95247215, 0.9599009 , 0.96291751, 0.98986343,
        0.98173598, 0.97077582, 0.95905482, 0.95306457, 0.95820642,
        0.95767593, 0.97296588, 0.99396408, 0.98767048, 0.95443742,
        0.93078599, 0.92789683, 0.92563312, 0.9447813 , 0.92955478,
        0.9300373 , 0.92250186, 0.92882532, 0.93845526, 0.94598413]),
 array([       nan,        nan,        nan,        nan, 0.01285917,
        0.01262091, 0.01284169, 0.01244436, 0.01125861, 0.01157958,
        0.01070001, 0.0103697 , 0.00956119, 0.00925407, 0.00881095,
        0.00858093, 0.00873133, 0.00899838, 0.0080794 , 0.00778765,
        0.0073583 , 0.00727159, 0.00741714, 0.00781652, 0.0069152 ,
        0.00671401, 0.00659136, 0.0063049 , 0.00634078, 0.00622797]),
 array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
        34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58]))

In [75]:
get_raw_data(g, 'Pseudomonas')

Pseudomonas Normalized growth rates Ab response, sem of growth rate, time


(array([       nan,        nan,        nan,        nan, 0.74525155,
        0.75886246, 0.78117818, 0.86566392, 0.87677197, 0.88897898,
        0.8985944 , 0.90113383, 0.9267672 , 0.92913503, 0.94899211,
        0.96876228, 0.9024046 , 0.90290379, 0.92847001, 0.92633354,
        0.93493814, 0.91992612, 0.89003661, 0.87485827, 0.87401562,
        0.93365829, 0.9541822 , 0.95556249, 0.94641423, 0.96898859]),
 array([       nan,        nan,        nan,        nan, 0.03009283,
        0.02999441, 0.02927807, 0.03044957, 0.02918595, 0.02923175,
        0.02930297, 0.02946964, 0.02935684, 0.02832303, 0.02822441,
        0.02558126, 0.02546288, 0.02926378, 0.02512366, 0.02512989,
        0.02612918, 0.02427002, 0.02164724, 0.02035272, 0.01983632,
        0.02133207, 0.02192958, 0.02160977, 0.02264006, 0.02252667]),
 array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
        34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58]))

In [76]:
get_raw_data(g, 'E.cocci')

E.cocci Normalized growth rates Ab response, sem of growth rate, time


(array([       nan,        nan,        nan,        nan, 0.85703907,
        0.76144327, 0.64629096, 0.55969912, 0.52292648, 0.52595241,
        0.55523161, 0.54525302, 0.51628178, 0.4767294 , 0.43835564,
        0.42772133, 0.40824958, 0.3717499 , 0.34480216, 0.33280291,
        0.298115  , 0.30677637, 0.3222829 , 0.32800226, 0.33789973,
        0.318117  , 0.33326739, 0.31447916, 0.28459449, 0.2858995 ]),
 array([       nan,        nan,        nan,        nan, 0.02224414,
        0.02010299, 0.01802622, 0.01645399, 0.0148828 , 0.01469416,
        0.01624273, 0.01780848, 0.01819888, 0.01835348, 0.01688723,
        0.01931451, 0.02070314, 0.022847  , 0.02082994, 0.02168627,
        0.02060741, 0.0234925 , 0.02889216, 0.02963325, 0.03068482,
        0.02675477, 0.03541671, 0.02796374, 0.02515206, 0.02506595]),
 array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
        34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58]))

In [78]:
get_raw_data(g, 'pool_no_Ab')

pool_no_Ab ones, sem of pooled growth rate, time


(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1]),
 array([       nan,        nan,        nan,        nan, 0.00633972,
        0.00577852, 0.00547524, 0.00513591, 0.00512915, 0.00482849,
        0.0045931 , 0.00456965, 0.0045441 , 0.00428424, 0.00395973,
        0.00401109, 0.00383023, 0.00373453, 0.00368219, 0.00371329,
        0.0036233 , 0.00350857, 0.00343896, 0.00336037, 0.00326281,
        0.00323048, 0.0031743 , 0.00317779, 0.00320466, 0.00318747]),
 array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
        34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58]))

In [79]:
get_raw_data(g, 'pool_Ab')

pool_Ab normalized growth rates, sem of pooled growth rate, time


(array([       nan,        nan,        nan,        nan, 0.91598728,
        0.92347352, 0.94040366, 0.94135683, 0.94351345, 0.95667808,
        0.95168594, 0.94988808, 0.95350887, 0.95077314, 0.95559964,
        0.95758019, 0.96483951, 0.97599091, 0.97461191, 0.9589875 ,
        0.94727483, 0.9482694 , 0.95019494, 0.96093877, 0.94538052,
        0.94616934, 0.942814  , 0.94309656, 0.94741249, 0.94887109]),
 array([       nan,        nan,        nan,        nan, 0.00583825,
        0.00571161, 0.00578255, 0.00574353, 0.00552377, 0.00541361,
        0.0051779 , 0.0051417 , 0.00512305, 0.00506047, 0.00504343,
        0.00469921, 0.00465484, 0.00477407, 0.00454136, 0.00441223,
        0.00427296, 0.00418511, 0.00413981, 0.00408362, 0.00382928,
        0.00374031, 0.00376313, 0.00367722, 0.00371354, 0.00365049]),
 array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
        34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58]))